services:
  redis:
    image: redis:7-alpine
    container_name: timebomb-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: timebomb-postgres
    environment:
      POSTGRES_DB: timebomb
      POSTGRES_USER: timebomb
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: timebomb-backend
    environment:
      NODE_ENV: production
      PORT: 3000
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://timebomb:password@postgres:5432/timebomb
      JWT_SECRET: ${JWT_SECRET:-your-production-secret-key}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
    depends_on:
      - redis
      - postgres
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: timebomb-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: