services:
  redis:
    image: redis:7-alpine
    container_name: timebomb-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: timebomb-postgres-dev
    environment:
      POSTGRES_DB: timebomb
      POSTGRES_USER: timebomb
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  redis_data_dev:
  postgres_data_dev: